import { useState } from "react";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import Header from "@/components/Header";
import TricolorBackground from "@/components/TricolorBackground";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { 
    ArrowLeft, ShoppingBag, FileText, Download, 
    Sparkles, Loader2, Copy, CheckCircle, ShieldAlert 
} from "lucide-react";
import { toast } from "sonner";
import { generateLegalContent } from "@/services/groqService";
import { exportStructuredPdf, toPlainText } from "@/lib/pdfExport";

const ConsumerComplaintPage = () => {
    const [formData, setFormData] = useState({
        seller: "",
        product: "",
        date: "",
        price: "",
        grievance: ""
    });
    const [isLoading, setIsLoading] = useState(false);
    const [draft, setDraft] = useState<string | null>(null);

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handleDraft = async () => {
        const { seller, product, grievance } = formData;
        if (!seller || !product || !grievance) {
            toast.error("Please fill in the mandatory details (Seller, Product, Grievance)");
            return;
        }

        setIsLoading(true);
        setDraft(null);

        try {
            const prompt = `Generate a formal Consumer Complaint letter based on:
            Seller: ${seller}
            Product: ${product}
            Date of Purchase: ${formData.date}
            Price: ${formData.price}
            Grievance Detail: ${grievance}`;
            
            const systemPrompt = "You are a Consumer Law expert in India. Draft a formal, legally-sound consumer grievance letter addressed to the seller. Use Consumer Protection Act, 2019 references and clearly state the expected remedy (Refund/Replacement/Compensation). Document structure: To, Date, Subject, Bodies of Text, Relief Sought, Signature.";
            
            const result = await generateLegalContent(prompt, systemPrompt);
            setDraft(result);
            toast.success("Draft generated!");
        } catch (error) {
            console.error("Drafting Error:", error);
            toast.error("Failed to draft complaint.");
        } finally {
            setIsLoading(false);
        }
    };

    const handleDownload = async () => {
        if (!draft) return;
        try {
            await exportStructuredPdf({
                title: "Consumer Complaint Draft",
                fileName: `Consumer_Complaint_${formData.seller.replace(/\s+/g, '_')}.pdf`,
                metadata: [`Subject: ${formData.product}`, `Date: ${new Date().toLocaleDateString()}`],
                sections: [{ text: toPlainText(draft) }],
                footer: "Generated by LegalAi India - Not a substitute for professional legal advice."
            });
            toast.success("Downloaded successfully!");
        } catch (error) {
            console.error("Download Error:", error);
            toast.error("PDF generation failed.");
        }
    };

    return (
        <div className="min-h-screen text-gray-900">
            <TricolorBackground intensity="strong" showOrbs={true} />
            <Header />

            <div className="container max-w-4xl mx-auto pt-24 pb-20 px-4 md:px-6">
                <Link to="/features" className="inline-flex items-center gap-2 text-gray-500 hover:text-saffron mb-8 transition-colors">
                    <ArrowLeft className="w-4 h-4" />
                    Back to AI Tools
                </Link>

                <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center mb-12">
                    <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-orange-500 text-white mb-6 shadow-premium">
                        <ShoppingBag className="w-8 h-8" />
                    </div>
                    <h1 className="text-4xl font-serif font-bold text-gray-900 mb-4">
                        Consumer <span className="premium-gradient-text">Complaint Draft</span>
                    </h1>
                    <p className="text-lg text-gray-500 max-w-2xl mx-auto">
                        Quickly generate a professionally-worded consumer grievance for defective products,
                        service delays, or unfair trade practices under Indian Consumer Laws.
                    </p>
                </motion.div>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-12">
                    <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} className="glass-tricolor-card p-6">
                        <div className="space-y-4">
                            <div>
                                <label className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-1 block">Seller / Business Name *</label>
                                <Input name="seller" value={formData.seller} onChange={handleInputChange} placeholder="e.g. Amazon India / Local Electronics Shop" className="border-gray-100" />
                            </div>
                            <div>
                                <label className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-1 block">Product / Service Name *</label>
                                <Input name="product" value={formData.product} onChange={handleInputChange} placeholder="e.g. iPhone 15 / House Repair Service" className="border-gray-100" />
                            </div>
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-1 block">Purchase Date</label>
                                    <Input name="date" type="date" value={formData.date} onChange={handleInputChange} className="border-gray-100" />
                                </div>
                                <div>
                                    <label className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-1 block">Paid Amount (₹)</label>
                                    <Input name="price" value={formData.price} onChange={handleInputChange} placeholder="e.g. 75000" className="border-gray-100" />
                                </div>
                            </div>
                            <div>
                                <label className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-1 block">Your Grievance Details *</label>
                                <Textarea name="grievance" value={formData.grievance} onChange={handleInputChange} placeholder="Describe the issue clearly (e.g. the product was delivered broken and customer care is not responding)..." className="min-h-[150px] border-gray-100" />
                            </div>
                            <Button onClick={handleDraft} disabled={isLoading} className="w-full h-14 btn-saffron rounded-xl uppercase tracking-widest font-bold">
                                {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : <><Sparkles className="w-5 h-5 mr-2" /> Draft Complaint</>}
                            </Button>
                        </div>
                    </motion.div>

                    <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }}>
                        {draft ? (
                            <div className="glass-premium rounded-3xl p-8 border border-gray-100 h-full flex flex-col">
                                <div className="flex items-center justify-between mb-6">
                                    <div className="flex items-center gap-2">
                                        <FileText className="w-5 h-5 text-saffron" />
                                        <span className="font-bold text-navy-india uppercase tracking-widest text-xs">AI_Generated_Draft</span>
                                    </div>
                                    <div className="flex gap-2">
                                        <Button variant="ghost" size="icon" onClick={() => { navigator.clipboard.writeText(draft); toast.success("Copied!"); }} className="rounded-full"><Copy className="w-4 h-4" /></Button>
                                        <Button variant="ghost" size="icon" onClick={handleDownload} className="rounded-full text-green-india"><Download className="w-4 h-4" /></Button>
                                    </div>
                                </div>
                                <div className="flex-1 overflow-y-auto max-h-[400px] text-sm text-gray-700 leading-relaxed font-serif whitespace-pre-wrap pr-2">
                                    {draft}
                                </div>
                                <div className="mt-6 p-4 bg-green-50 rounded-xl border border-green-100 flex items-center gap-3">
                                    <CheckCircle className="w-5 h-5 text-green-600" />
                                    <span className="text-xs text-green-800 font-medium tracking-tight">Draft complies with CPA 2019 guidelines. Ready for sending.</span>
                                </div>
                            </div>
                        ) : (
                            <div className="h-full flex flex-col items-center justify-center border-2 border-dashed border-gray-100 rounded-3xl p-12 text-center bg-white/40">
                                <ShieldAlert className="w-12 h-12 text-gray-200 mb-4" />
                                <h3 className="text-xl font-serif font-bold text-gray-400">Ready to Draft</h3>
                                <p className="text-sm text-gray-400 max-w-xs mt-2">Fill the form to the left to generate your consumer grievance letter using AI.</p>
                            </div>
                        )}
                    </motion.div>
                </div>

                <div className="text-center">
                    <p className="text-[10px] text-gray-400 max-w-2xl mx-auto uppercase tracking-widest font-mono">
                        Informational tool provided for educational clarity. Not a substitute for professional legal advice.
                    </p>
                </div>
            </div>
            <Footer />
        </div>
    );
};

export default ConsumerComplaintPage;
