import { useState } from "react";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import Header from "@/components/Header";
import TricolorBackground from "@/components/TricolorBackground";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { 
    ArrowLeft, ShieldAlert, FileText, Download, Sparkles, 
    Loader2, Copy, CheckCircle, Shield, Monitor, Send
} from "lucide-react";
import { toast } from "sonner";
import { generateLegalContent } from "@/services/groqService";
import { exportStructuredPdf, toPlainText } from "@/lib/pdfExport";

const CyberCrimeReporterPage = () => {
    const [formData, setFormData] = useState({
        crimeType: "",
        incidentDate: "",
        incidentTime: "",
        platform: "",
        suspectDetails: "",
        description: "",
        evidenceAvailable: ""
    });
    const [isLoading, setIsLoading] = useState(false);
    const [reportDraft, setReportDraft] = useState<string | null>(null);

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handleGenerate = async () => {
        const { crimeType, incidentDate, description } = formData;
        if (!crimeType || !incidentDate || !description) {
            toast.error("Please provide at least Crime Type, Date, and Description.");
            return;
        }

        setIsLoading(true);
        setReportDraft(null);

        try {
            const prompt = `Draft a formal Cyber Crime Complaint for Indian Police:
            Type of Crime: ${crimeType}
            Incident Occurrence: ${incidentDate} at ${formData.incidentTime}
            Platform/Website: ${formData.platform}
            Suspect Info (URLs, Handles, Phone): ${formData.suspectDetails}
            Incident Particulars: ${description}
            Evidence (Screenshots/Logs available): ${formData.evidenceAvailable}`;

            const systemPrompt = "You are a Cyber Law Expert and Digital Forensics specialist in India. Draft a detailed formal complaint for a cyber crime. Include legal references (e.g., Information Technology Act, 2000, sections like 66D, 67, etc. if applicable) and explicit instructions on what digital evidence is being preserved. Format as a formal application to the SHO (Station House Officer) or the Cyber Cell.";

            const result = await generateLegalContent(prompt, systemPrompt);
            setReportDraft(result);
            toast.success("Cyber Complaint Drafted!");
        } catch (error) {
            console.error("Cyber Crime Error:", error);
            toast.error("Failed to generate report draft.");
        } finally {
            setIsLoading(false);
        }
    };

    const handleDownload = async () => {
        if (!reportDraft) return;
        try {
            await exportStructuredPdf({
                title: "Cyber Crime Complaint Draft",
                fileName: `Cyber_Complaint_${formData.crimeType.replace(/\s+/g, '_')}.pdf`,
                metadata: [`Type: ${formData.crimeType}`, `Date: ${new Date().toLocaleDateString()}`],
                sections: [{ text: toPlainText(reportDraft) }],
                footer: "Generated by LegalAi India - Information Technology Act, 2000 compliance."
            });
            toast.success("Downloaded successfully!");
        } catch (error) {
            console.error("Download Error:", error);
            toast.error("PDF generation failed.");
        }
    };

    return (
        <div className="min-h-screen text-gray-900">
            <TricolorBackground intensity="strong" showOrbs={true} />
            <Header />

            <div className="container max-w-5xl mx-auto pt-24 pb-20 px-4 md:px-6">
                <Link to="/features" className="inline-flex items-center gap-2 text-gray-500 hover:text-saffron mb-8 transition-colors">
                    <ArrowLeft className="w-4 h-4" />
                    Back to AI Tools
                </Link>

                <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center mb-12">
                    <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-red-600 text-white mb-6 shadow-premium">
                        <Monitor className="w-8 h-8" />
                    </div>
                    <h1 className="text-4xl font-serif font-bold text-gray-900 mb-4">
                        Cyber <span className="premium-gradient-text">Crime Reporter</span>
                    </h1>
                    <p className="text-lg text-gray-500 max-w-2xl mx-auto">
                        Report cyber fraud, harassment, or online crime formally. We help you 
                        draft a legally-sound complaint for the National Cyber Crime portal 
                        or local Cyber Cell.
                    </p>
                </motion.div>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-12">
                    <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} className="glass-tricolor-card p-6">
                        <div className="space-y-4">
                            <div>
                                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1 block">Nature of Crime *</label>
                                <Input name="crimeType" value={formData.crimeType} onChange={handleInputChange} placeholder="e.g. Financial Fraud, Identity Theft, Harassment" className="h-11 border-gray-100" />
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1 block">Incident Date *</label>
                                    <Input name="incidentDate" type="date" value={formData.incidentDate} onChange={handleInputChange} className="h-11 border-gray-100" />
                                </div>
                                <div>
                                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1 block">Incident Time</label>
                                    <Input name="incidentTime" type="time" value={formData.incidentTime} onChange={handleInputChange} className="h-11 border-gray-100" />
                                </div>
                            </div>

                            <div>
                                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1 block">Platform / App Name</label>
                                <Input name="platform" value={formData.platform} onChange={handleInputChange} placeholder="e.g. Instagram, WhatsApp, Banking App" className="h-11 border-gray-100" />
                            </div>

                            <div>
                                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1 block">Suspect ID / Phone / URL</label>
                                <Input name="suspectDetails" value={formData.suspectDetails} onChange={handleInputChange} placeholder="User handles, phone numbers, or fraudulent links" className="h-11 border-gray-100" />
                            </div>

                            <div>
                                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1 block">Detailed Description *</label>
                                <Textarea name="description" value={formData.description} onChange={handleInputChange} placeholder="Explain exactly what happened, step by step..." className="min-h-[140px] border-gray-100" />
                            </div>

                            <div>
                                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1 block">Evidence Preserved (List them)</label>
                                <Textarea name="evidenceAvailable" value={formData.evidenceAvailable} onChange={handleInputChange} placeholder="List screenshots, UTR numbers, email headers, etc." className="min-h-[70px] border-gray-100" />
                            </div>

                            <Button onClick={handleGenerate} disabled={isLoading} className="w-full h-14 btn-navy rounded-xl uppercase tracking-widest font-bold">
                                {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : <><Send className="w-5 h-5 mr-2" /> Draft Formal Report</>}
                            </Button>
                        </div>
                    </motion.div>

                    <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }}>
                        {reportDraft ? (
                            <div className="glass-premium rounded-3xl p-8 border border-gray-100 h-full flex flex-col">
                                <div className="flex items-center justify-between mb-6">
                                    <div className="flex items-center gap-2">
                                        <ShieldAlert className="w-5 h-5 text-red-500" />
                                        <span className="font-bold text-red-600 uppercase tracking-widest text-[10px]">CYBER_OFFENSE_REPORT_DRAFT</span>
                                    </div>
                                    <div className="flex gap-2">
                                        <Button variant="ghost" size="icon" onClick={() => { navigator.clipboard.writeText(reportDraft); toast.success("Copied!"); }} className="rounded-full"><Copy className="w-4 h-4" /></Button>
                                        <Button variant="ghost" size="icon" onClick={handleDownload} className="rounded-full text-green-india"><Download className="w-4 h-4" /></Button>
                                    </div>
                                </div>
                                <div className="flex-1 overflow-y-auto max-h-[500px] text-sm text-gray-700 leading-relaxed font-serif whitespace-pre-wrap pr-2">
                                    {reportDraft}
                                </div>
                                <div className="mt-8 p-6 bg-red-50 rounded-[2rem] border border-red-100 relative overflow-hidden">
                                    <div className="absolute top-0 left-0 w-1 h-full bg-red-600 opacity-50" />
                                    <div className="flex items-start gap-4">
                                        <div className="w-10 h-10 rounded-xl bg-white flex items-center justify-center shrink-0 shadow-sm">
                                            <Shield className="w-6 h-6 text-red-600" />
                                        </div>
                                        <div>
                                            <h4 className="text-sm font-bold text-red-900 mb-1 tracking-tight">Crucial Advice</h4>
                                            <p className="text-xs text-red-800/80 leading-relaxed italic">
                                                In case of financial fraud, immediately call <span className="font-bold">1930</span> or visit <span className="font-bold underline">cybercrime.gov.in</span> within the "Golden Hour" (first 2 hours).
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        ) : (
                            <div className="h-full flex flex-col items-center justify-center border-2 border-dashed border-gray-100 rounded-3xl p-12 text-center bg-white/40">
                                <Monitor className="w-12 h-12 text-gray-200 mb-4" />
                                <h3 className="text-xl font-serif font-bold text-gray-400">Reporter Waiting</h3>
                                <p className="text-sm text-gray-400 max-w-xs mt-2">Enter the incident details to compile a formal cyber crime report draft.</p>
                            </div>
                        )}
                    </motion.div>
                </div>
            </div>
            <Footer />
        </div>
    );
};

export default CyberCrimeReporterPage;
