import { useState } from "react";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import Header from "@/components/Header";
import TricolorBackground from "@/components/TricolorBackground";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { 
    ArrowLeft, BookOpen, Sparkles, Loader2, 
    Copy, CheckCircle, FileText, Gavel, Scale, 
    Search, Download
} from "lucide-react";
import { toast } from "sonner";
import { generateLegalContent } from "@/services/groqService";
import { exportStructuredPdf, toPlainText } from "@/lib/pdfExport";

const JudgmentSimplifierPage = () => {
    const [judgment, setJudgment] = useState("");
    const [isLoading, setIsLoading] = useState(false);
    const [summary, setSummary] = useState<string | null>(null);

    const handleSimplify = async () => {
        if (!judgment.trim()) return;

        setIsLoading(true);
        setSummary(null);

        try {
            const systemPrompt = "You are a specialized Legal Judgment Simplifier for the Indian Judicial System. Extract: 1. Case Name & Parties, 2. Core Legal Issue, 3. Facts of the Case, 4. Final Ratio Decidendi (Principle of Law), 5. Order/Verdict. Simplify the complex legal language and present it clearly.";
            const result = await generateLegalContent(judgment, systemPrompt);
            setSummary(result);
            toast.success("Judgment simplified!");
        } catch (error) {
            console.error("Simplifier Error:", error);
            toast.error("Failed to simplify judgment.");
        } finally {
            setIsLoading(false);
        }
    };

    const handleDownload = async () => {
        if (!summary) return;
        try {
            await exportStructuredPdf({
                title: "Judgment Summary",
                fileName: "LegalAI_Simplified_Judgment.pdf",
                metadata: [`Generated On: ${new Date().toLocaleDateString()}`],
                sections: [{ text: toPlainText(summary) }],
                footer: "Generated by LegalAi India - Professional Legal Intelligence."
            });
            toast.success("Downloaded!");
        } catch (error) {
            console.error("Download Error:", error);
            toast.error("PDF generation failed.");
        }
    };

    return (
        <div className="min-h-screen text-gray-900">
            <TricolorBackground intensity="strong" showOrbs={true} />
            <Header />

            <div className="container max-w-4xl mx-auto pt-24 pb-20 px-4 md:px-6">
                <Link to="/features" className="inline-flex items-center gap-2 text-gray-500 hover:text-saffron mb-8 transition-colors">
                    <ArrowLeft className="w-4 h-4" />
                    Back to AI Tools
                </Link>

                <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center mb-12">
                    <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-navy-india text-white mb-6 shadow-premium">
                        <FileText className="w-8 h-8" />
                    </div>
                    <h1 className="text-4xl font-serif font-bold text-gray-900 mb-4">
                        Judgment <span className="premium-gradient-text">Simplifier</span>
                    </h1>
                    <p className="text-lg text-gray-500 max-w-2xl mx-auto">
                        Extract the 'Ratio Decidendi' from complex legal orders. Our AI analyzes 
                        Indian court judgments and simplifies them into key facts, issues, and principles.
                    </p>
                </motion.div>

                <div className="space-y-8">
                    <motion.div initial={{ opacity: 0, scale: 0.98 }} animate={{ opacity: 1, scale: 1 }} className="glass-tricolor-card p-8">
                        <div>
                            <label className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-3 block">Paste Full Judgment below *</label>
                            <Textarea 
                                value={judgment} 
                                onChange={(e) => setJudgment(e.target.value)} 
                                placeholder="Paste the judgment or court order text here..." 
                                className="min-h-[250px] border-gray-100 italic font-serif leading-relaxed" 
                            />
                        </div>
                        <Button 
                            onClick={handleSimplify} 
                            disabled={isLoading || !judgment.trim()} 
                            className="w-full h-14 btn-navy rounded-xl uppercase tracking-widest font-bold mt-6"
                        >
                            {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : <><Gavel className="w-5 h-5 mr-2" /> Simplify Order</>}
                        </Button>
                    </motion.div>

                    {summary && (
                        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="glass-premium rounded-[3rem] p-10 border border-gray-100 relative overflow-hidden shadow-2xl">
                            <div className="absolute top-0 left-0 w-2 h-full bg-navy-india" />
                            
                            <div className="flex items-center justify-between mb-8">
                                <div className="flex items-center gap-3">
                                    <Sparkles className="w-5 h-5 text-saffron" />
                                    <span className="font-mono text-[10px] font-bold text-gray-400 uppercase tracking-widest">Simplified_Intelligence</span>
                                </div>
                                <div className="flex gap-2">
                                    <Button onClick={() => { navigator.clipboard.writeText(summary); toast.success("Copied!"); }} variant="ghost" size="sm" className="rounded-full"><Copy className="w-4 h-4 mr-2" /> Copy</Button>
                                    <Button onClick={handleDownload} variant="ghost" size="sm" className="rounded-full text-green-india"><Download className="w-4 h-4 mr-2" /> Export PDF</Button>
                                </div>
                            </div>

                            <div className="prose prose-lg max-w-none text-gray-800 font-serif whitespace-pre-wrap leading-relaxed">
                                {summary}
                            </div>

                            <div className="mt-12 pt-8 border-t border-gray-100 grid grid-cols-2 gap-4">
                                <div className="flex items-start gap-3">
                                    <Scale className="w-6 h-6 text-saffron" />
                                    <p className="text-[10px] text-gray-400 leading-tight">AI extracted the core legal logic of the case. Verify against original order for precision.</p>
                                </div>
                                <div className="flex items-start gap-3">
                                    <Search className="w-6 h-6 text-blue-600" />
                                    <p className="text-[10px] text-gray-400 leading-tight">Principle of law identified for your legal research.</p>
                                </div>
                            </div>
                        </motion.div>
                    )}
                </div>
            </div>
            <Footer />
        </div>
    );
};

export default JudgmentSimplifierPage;
