import { useState } from "react";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import Header from "@/components/Header";
import TricolorBackground from "@/components/TricolorBackground";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { 
    ArrowLeft, FileText, Download, Sparkles, 
    Loader2, Copy, CheckCircle, Info, Landmark 
} from "lucide-react";
import { toast } from "sonner";
import { generateLegalContent } from "@/services/groqService";
import { exportStructuredPdf, toPlainText } from "@/lib/pdfExport";

const RTIGeneratorPage = () => {
    const [formData, setFormData] = useState({
        department: "",
        officeAddress: "",
        subject: "",
        description: "",
        periodStart: "",
        periodEnd: "",
        applicantName: "",
        applicantAddress: ""
    });
    const [isLoading, setIsLoading] = useState(false);
    const [rtiDraft, setRtiDraft] = useState<string | null>(null);

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handleGenerate = async () => {
        const { department, subject, description, applicantName } = formData;
        if (!department || !subject || !description || !applicantName) {
            toast.error("Please fill in all mandatory fields.");
            return;
        }

        setIsLoading(true);
        setRtiDraft(null);

        try {
            const prompt = `Draft a formal RTI (Right to Information) application for India:
            Target Department: ${department}
            Office Address: ${formData.officeAddress}
            Subject: ${subject}
            Information Required: ${description}
            Period: ${formData.periodStart} to ${formData.periodEnd}
            Applicant Name: ${applicantName}
            Applicant Address: ${formData.applicantAddress}`;

            const systemPrompt = "You are an RTI Export for the Government of India. Draft a professional RTI application as per the Right to Information Act, 2005. Include: To, From, Subject, Details of Information required, Period of info, Fees details (standard ₹10), and Declaration. Use a formal, authoritative tone.";

            const result = await generateLegalContent(prompt, systemPrompt);
            setRtiDraft(result);
            toast.success("RTI Application drafted!");
        } catch (error) {
            console.error("RTI Error:", error);
            toast.error("Failed to generate RTI draft.");
        } finally {
            setIsLoading(false);
        }
    };

    const handleDownload = async () => {
        if (!rtiDraft) return;
        try {
            await exportStructuredPdf({
                title: "RTI Application Draft",
                fileName: `RTI_${formData.department.replace(/\s+/g, '_')}.pdf`,
                metadata: [`Department: ${formData.department}`, `Date: ${new Date().toLocaleDateString()}`],
                sections: [{ text: toPlainText(rtiDraft) }],
                footer: "Generated by LegalAi India - Right to Information Act, 2005."
            });
            toast.success("Downloaded successfully!");
        } catch (error) {
            console.error("Download Error:", error);
            toast.error("PDF generation failed.");
        }
    };

    return (
        <div className="min-h-screen text-gray-900">
            <TricolorBackground intensity="strong" showOrbs={true} />
            <Header />

            <div className="container max-w-5xl mx-auto pt-24 pb-20 px-4 md:px-6">
                <Link to="/features" className="inline-flex items-center gap-2 text-gray-500 hover:text-saffron mb-8 transition-colors">
                    <ArrowLeft className="w-4 h-4" />
                    Back to AI Tools
                </Link>

                <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-center mb-12">
                    <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-blue-600 text-white mb-6 shadow-premium">
                        <Landmark className="w-8 h-8" />
                    </div>
                    <h1 className="text-4xl font-serif font-bold text-gray-900 mb-4">
                        RTI <span className="premium-gradient-text">Application Generator</span>
                    </h1>
                    <p className="text-lg text-gray-500 max-w-2xl mx-auto">
                        Exercise your Right to Information. Generate a perfectly formatted RTI 
                        application according to the RTI Act, 2005 in seconds.
                    </p>
                </motion.div>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-12">
                    <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} className="glass-tricolor-card p-6">
                        <div className="space-y-4">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div>
                                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1 block">Public Authority / Dept *</label>
                                    <Input name="department" value={formData.department} onChange={handleInputChange} placeholder="e.g. Municipal Corp of Delhi" className="h-11 border-gray-100" />
                                </div>
                                <div>
                                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1 block">Applicant Name *</label>
                                    <Input name="applicantName" value={formData.applicantName} onChange={handleInputChange} placeholder="Your Full Name" className="h-11 border-gray-100" />
                                </div>
                            </div>

                            <div>
                                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1 block">Department Address</label>
                                <Input name="officeAddress" value={formData.officeAddress} onChange={handleInputChange} placeholder="Complete office address if known" className="h-11 border-gray-100" />
                            </div>

                            <div>
                                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1 block">Subject of RTI *</label>
                                <Input name="subject" value={formData.subject} onChange={handleInputChange} placeholder="e.g. Road repair funds utilization for Sector 5" className="h-11 border-gray-100" />
                            </div>

                            <div>
                                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1 block">Details of Information Required *</label>
                                <Textarea name="description" value={formData.description} onChange={handleInputChange} placeholder="Be specific about the information, files, or documents you need..." className="min-h-[120px] border-gray-100" />
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1 block">Period From</label>
                                    <Input name="periodStart" type="date" value={formData.periodStart} onChange={handleInputChange} className="h-11 border-gray-100" />
                                </div>
                                <div>
                                    <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1 block">Period To</label>
                                    <Input name="periodEnd" type="date" value={formData.periodEnd} onChange={handleInputChange} className="h-11 border-gray-100" />
                                </div>
                            </div>

                            <div>
                                <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1 block">Applicant Address</label>
                                <Textarea name="applicantAddress" value={formData.applicantAddress} onChange={handleInputChange} placeholder="Address for receiving the information by post" className="min-h-[80px] border-gray-100" />
                            </div>

                            <Button onClick={handleGenerate} disabled={isLoading} className="w-full h-14 btn-navy rounded-xl uppercase tracking-widest font-bold">
                                {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : <><Sparkles className="w-5 h-5 mr-2" /> Generate RTI Draft</>}
                            </Button>
                        </div>
                    </motion.div>

                    <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }}>
                        {rtiDraft ? (
                            <div className="glass-premium rounded-3xl p-8 border border-gray-100 h-full flex flex-col">
                                <div className="flex items-center justify-between mb-6">
                                    <div className="flex items-center gap-2">
                                        <FileText className="w-5 h-5 text-saffron" />
                                        <span className="font-bold text-navy-india uppercase tracking-widest text-xs">OFFICIAL_RTI_DRAFT</span>
                                    </div>
                                    <div className="flex gap-2">
                                        <Button variant="ghost" size="icon" onClick={() => { navigator.clipboard.writeText(rtiDraft); toast.success("Copied!"); }} className="rounded-full"><Copy className="w-4 h-4" /></Button>
                                        <Button variant="ghost" size="icon" onClick={handleDownload} className="rounded-full text-green-india"><Download className="w-4 h-4" /></Button>
                                    </div>
                                </div>
                                <div className="flex-1 overflow-y-auto max-h-[500px] text-sm text-gray-700 leading-relaxed font-serif whitespace-pre-wrap pr-2">
                                    {rtiDraft}
                                </div>
                                <div className="mt-8 p-4 bg-blue-50 rounded-xl border border-blue-100 flex items-start gap-3">
                                    <Info className="w-5 h-5 text-blue-600 mt-0.5" />
                                    <div className="text-xs text-blue-800 leading-relaxed font-medium">
                                        Note: A standard RTI fee of ₹10 is required. You can pay via Postal Order, Bank Draft, or online portal if applicable.
                                    </div>
                                </div>
                            </div>
                        ) : (
                            <div className="h-full flex flex-col items-center justify-center border-2 border-dashed border-gray-100 rounded-3xl p-12 text-center bg-white/40">
                                <Landmark className="w-12 h-12 text-gray-200 mb-4" />
                                <h3 className="text-xl font-serif font-bold text-gray-400">Ready to Draft</h3>
                                <p className="text-sm text-gray-400 max-w-xs mt-2">Fill the RTI requirements to get a professionally worded application draft.</p>
                            </div>
                        )}
                    </motion.div>
                </div>
            </div>
            <Footer />
        </div>
    );
};

export default RTIGeneratorPage;
